### ISSUE TITLE
Unable to use FluentAssertions in NUnit3 async scenarios

### ISSUE THREAD

**Issue by sgoodgrove** [LightBDD/LightBDD#237]
### Description

If I define an async scenario (NUnit3) and make a failing assertion the Visual Studio test runner reports the test as having passed although the LightBBD log does suggest that the scenario failed.

### e.g.

```cs
using System.Threading.Tasks;

using FluentAssertions;

using LightBDD.Framework.Scenarios;
using LightBDD.NUnit3;

using NUnit.Framework;

namespace LighBDDTestNs
{
    public class LightBDDTest : FeatureFixture
    {
        [Scenario]
        public void Scenario1() => Runner.RunScenarioAsync(FluentFail);

        private Task FluentFail()
        {
            "Hello world".Should().Be("Hello");
            Assert.That("Hello world", Is.EqualTo("Hello"));
            return Task.CompletedTask;
        }
    }
}
```

In the above code if I comment out the FluentAssertions line `"Hello world".Should().Be("Hello")` then the test runner does report a failing test.

### LightBDD output

This is the LightBDD output when the test passes

```
SCENARIO: Scenario1
  STEP 1/1: FluentFail...
  STEP 1/1: FluentFail (Failed after 183ms)
  SCENARIO RESULT: Failed after 206ms
    Step 1: NUnit.Framework.AssertionException : Expected string to be 
    	"Hello" with a length of 5, but 
    	"Hello world" has a length of 11, differs near " wo" (index 5).
    	at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\LateBoundTestFramework.cs:line 13
    	at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\TestFrameworkProvider.cs:line 40
    	at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\DefaultAssertionStrategy.cs:line 29
    	at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 223
    	at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 196
    	at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringEqualityValidator.cs:line 31
    	at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringValidator.cs:line 41
    	at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringAssertions.cs:line 39
```

My actual test method and code does make use of the `async` /  `await` keywords, but this example boils it down to its simplest form and behaves in the same way.

**Comment by Suremaker** [comment]
Hello @sgoodgrove ,

Please take a look that `Runner.RunScenarioAsync()` is an asynchronous method, however, your `Scenario1()` method is not asynchronous and it does not await the scenario outcome. What happens here is that the nunit framework finishes the test execution without (a)waiting for the scenario result, thus it does not have a chance to capture your assertion exception.

To visualize it better, your test method is an equivalent of this:
```c#
[Scenario]
public void Scenario1()
{
    Runner.RunScenarioAsync(FluentFail); //not capturing the scenario results
}
```

To properly propagate the test results, it needs to be either:
```c#
[Scenario]
public Task Scenario1()
{
    return Runner.RunScenarioAsync(FluentFail);
}
```

or

```c#
[Scenario]
public async Task Scenario1()
{
    await Runner.RunScenarioAsync(FluentFail);
}
```

I hope it helps :)

**Comment by sgoodgrove** [comment]
🤦 

I feel foolish now. Yes, setting the signature to return `Task` does resolve that.
Thanks for your help.

**Comment by Suremaker** [comment]
No problem :) I hope you enjoy the library.

Cheers
