### ISSUE TITLE
LightBDD.NUnit3 - display immediate progress of executed tests

### ISSUE THREAD

**Issue by Suremaker** [LightBDD/LightBDD#34]
Currently LightBDD.NUnit3 uses `TestContext.Out` to render scenario progress, which effects with whole test output being displayed at the end of test case.

The integration should be changed to use:
* `TestContext.Progress` for reporting execution progress (it will be displayed immediately),
* `ParallelProgressNotifierProvider` instead of `DefaultProgressNotifier` to render progress in more readable manner for parallel execution.

----
Update after lack of nunit support in https://github.com/nunit/nunit/issues/2177:
* `TestContext.Progress` will be used in conjunction with `ParallelProgressNotifierProvider` to display immediate progress,
* `TestContext.Out` will be still used in conjunction with `DefaultProgressNotifier` to display execution summary in test output windows (VS Test Explorer and Resharper) after they are finished,
* test progress notification configuration will be extended to allow change the default behavior in more manageable manner

Progress:
- [x] Default progress notifiers are reconfigured to report immediate progress and summary,
- [x] Progress notification configuration methods are extended to support easier customization,
- [x] Example test scripts are updated to suggest the best configuration of test runners,
- [x] Documentation is updated,
- [x] LightBDD.NUnit3 notifiers are updated,
- [x] LightBDD.XUnit2 notifiers are updated.

**Comment by Suremaker** [comment]
Blocked by https://github.com/nunit/nunit/issues/2177

**Comment by Suremaker** [comment]
Currently, it is not possible to provide perfect implementation of progress notification due to nunit3 limitations:
* TestContext.Progress prints execution progress in real-time but it's not captured in output window of Visual Studio Test Explorer nor Resharper,
* TestContext.Out allows to capture progress and display in output window of VS Test Explorer and Resharper, but does not display the progress in real-time on console.

As getting real-time progress of acceptance tests is important, a non perfect approach will be implemented where both methods will be used at the same time.

It will allow to track test execution in real-time on:
* Output window `Tests` channel in Visual Studio,
* `dotnet-test` and `nunit3-console.exe`.

The downside of this approach will be that console applications will display all steps twice - once as they are being executed (real-time progress) and then as a test summary.

While the new behavior will be enabled by default, the progress notification configuration methods will be extended to allow disabling the new functionality (more details will be provided during feature implementation)

**Comment by Suremaker** [comment]
Changes: 
* LightBDD.NUnit3 prints now the immediate progress on console with `dotnet test` and `nunit3-console.exe` in format like:
    ```
    Fi=000,Fa=000,Pe=003 #  1> SCENARIO: [Ticket-6] No product in stock
    Fi=000,Fa=000,Pe=003 #  2> SCENARIO: [Ticket-3] Anonymous login name should allow to log in
    Fi=000,Fa=000,Pe=003 #  3> SCENARIO: [Ticket-12] Ordering products
    Fi=000,Fa=000,Pe=003 #  2>   STEP 1/5: GIVEN the user is about to login...
    Fi=000,Fa=000,Pe=003 #  3>   STEP 1/4: GIVEN customer is logged in...
    Fi=000,Fa=000,Pe=003 #  1>   STEP 1/4: GIVEN product is out of stock...
    Fi=000,Fa=000,Pe=003 #  3>   STEP 1.1/1.5: GIVEN the user is about to login...
    Fi=000,Fa=000,Pe=003 #  2>   STEP 1/5: GIVEN the user is about to login (Passed after 13ms)
    Fi=000,Fa=000,Pe=003 #  1>   STEP 1/4: GIVEN product is out of stock (Passed after 13ms)
    ```
    and the scenario summary (displayed by VS / Resharper / test outcome) in format like:
    ```
    Skipped  Ordering_products
    Error Message:
     Not implemented yet
    Standard Output Messages:
     SCENARIO: [Ticket-12] Ordering products
       STEP 1/4: GIVEN customer is logged in...
       STEP 1.1/1.5: GIVEN the user is about to login...
       STEP 1.1/1.5: GIVEN the user is about to login (Passed after <1ms)
       STEP 1.2/1.5: AND the user entered valid login...
       STEP 1.2/1.5: AND the user entered valid login (Passed after <1ms)
       STEP 1.3/1.5: AND the user entered valid password...
       STEP 1.3/1.5: AND the user entered valid password (Passed after <1ms)
       STEP 1.4/1.5: WHEN the user clicks login button...
       STEP 1.4/1.5: WHEN the user clicks login button (Passed after 1s 151ms)
       STEP 1.5/1.5: THEN the login operation should be successful...
       STEP 1.5/1.5: THEN the login operation should be successful (Passed after <1ms)
       STEP 1/4: GIVEN customer is logged in (Passed after 1s 201ms)
       STEP 2/4: WHEN customer adds products to basket...
       STEP 2.1/2.3: GIVEN product "wooden desk" is in stock...
       STEP 2.1/2.3: GIVEN product "wooden desk" is in stock (Passed after 1ms)
       STEP 2.2/2.3: WHEN customer adds product "wooden desk" to the basket...
       STEP 2.2/2.3: WHEN customer adds product "wooden desk" to the basket (Bypassed after 1s 900ms)
       STEP 2.3/2.3: THEN the product addition should be successful...
       STEP 2.3/2.3: THEN the product addition should be successful (Passed after 1ms)
       STEP 2/4: WHEN customer adds products to basket (Bypassed after 1s 912ms)
       STEP 3/4: AND customer pays for products in basket...
       STEP 3.1/3.2: WHEN customer requests to pay...
       STEP 3.1/3.2: WHEN customer requests to pay (Passed after 1s 200ms)
       STEP 3.2/3.2: THEN payment should be successful...
       STEP 3.2/3.2: THEN payment should be successful (Passed after <1ms)
       STEP 3/4: AND customer pays for products in basket (Passed after 1s 202ms)
       STEP 4/4: THEN customer should receive order email...
       STEP 4.1/4.2: THEN customer should receive invoice...
       STEP 4.1/4.2: THEN customer should receive invoice (Ignored after 4ms)
       STEP 4/4: THEN customer should receive order email (Ignored after 26ms)
       SCENARIO RESULT: Ignored after 4s 370ms
         Step 2.2: Until proper api is implemented, product is added directly to the DB.
         Step 4.1: Not implemented yet
    ``` 
* LightBDD.XUnit2 has been updated to print scenario summary in format like:
    ```
    Example.LightBDD.XUnit2.Features.Login_feature.Anonymous_login_name_should_allow_to_log_in [FAIL]
      Login should succeeded
      Expected: True
      Actual:   False
      Stack Trace:
        d:\dev\LightBDD_234\examples\Example.LightBDD.XUnit2\Features\Login_feature.Steps.cs(57,0): at Example.LightBDD.XUnit2.Features.Login_feature.Then_the_login_operation_should_be_successful()
        d:\dev\LightBDD_234\src\LightBDD.Framework\Scenarios\Basic\Implementation\BasicStepCompiler.cs(81,0): at LightBDD.Framework.Scenarios.Basic.Implementation.BasicStepCompiler.StepExecutor.Execute(Object context, Object[] args)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        d:\dev\LightBDD_234\src\LightBDD.Framework\Scenarios\Basic\BasicScenarioExtensions.cs(54,0): at LightBDD.Framework.Scenarios.Basic.BasicScenarioExtensions.RunScenario(IBddRunner runner, Action[] steps)
        d:\dev\LightBDD_234\examples\Example.LightBDD.XUnit2\Features\Login_feature.cs(85,0): at Example.LightBDD.XUnit2.Features.Login_feature.Anonymous_login_name_should_allow_to_log_in()
      Output:
        SCENARIO: [Ticket-3] Anonymous login name should allow to log in
          STEP 1/5: GIVEN the user is about to login...
          STEP 1/5: GIVEN the user is about to login (Passed after <1ms)
          STEP 2/5: AND the user entered anonymous login...
          STEP 2/5: /* Presentation of failed scenario */
          STEP 2/5: AND the user entered anonymous login (Passed after <1ms)
          STEP 3/5: WHEN the user clicks login button...
          STEP 3/5: WHEN the user clicks login button (Passed after 1s 516ms)
          STEP 4/5: THEN the login operation should be successful...
          STEP 4/5: THEN the login operation should be successful (Failed after 4ms)
          SCENARIO RESULT: Failed after 1s 537ms
    ```
    while immediate progress is printed in format like before.
* The `FeatureProgressNotifierConfiguration` and `ScenarioProgressNotifierConfiguration` has been extended with methods allowing to combine currently configured notifiers with new ones as well as clear them:
    ```
    configuration.Get<FeatureProgressNotifierConfiguration>()
        .ClearNotifiers()
        .AppendNotifiers(new CustomFeatureProgressNotifier())
        .AppendNotifiers(new CustomFeatureProgressNotifier2());

    configuration.Get<ScenarioProgressNotifierConfiguration>()
        .ClearNotifierProviders()
        .AppendNotifierProviders(() => new CustomScenarioProgressNotifier())
        .AppendNotifierProviders<FeatureFixture>(fixture => new CustomScenarioProgressNotifier2(fixture));
    ```
* All integrations (LightBDD.NUnit2, LightBDD.NUnit3, LightBDD.XUnit2, LightBDD.MsTest2) have been updated with configuration methods allowing to apply default progress notifiers after they have been cleaned up:
    ```
    configuration.Get<FeatureProgressNotifierConfiguration>()
        .ClearNotifiers()
        .AppendFrameworkDefaultProgressNotifiers();

    configuration.Get<ScenarioProgressNotifierConfiguration>()
        .ClearNotifierProviders()
        .AppendFrameworkDefaultProgressNotifiers();
    ```
