### ISSUE TITLE
 Allow IReportFormatter and IGlobalResourceSetUp implementations to use LightBDDConfigurationAware

### ISSUE THREAD

**Issue by goldsam** [LightBDD/LightBDD#344]
#### Description
An `IReportWriter` implementation that extends `LightBddConfigurationAware` will fail when referencinh the `Configuration` property inside the `Save` method. This leads to fun exception traces like this:

```
 Catastrophic failure: System.InvalidOperationException: LightBDD is not initialized yet.
   at LightBDD.Core.Execution.Coordination.FeatureCoordinator.GetInstance()
   at LightBDD.Core.Extensibility.LightBddConfigurationAware.get_Configuration()
   at TestResultReportFileWriter.Save(IFeatureResult[] results) in C:\[REDACTED]\TestResultReportFileWriter.cs:line 33
   at LightBDD.Core.Reporting.FeatureReportGenerator.Dispose()
   at LightBDD.Core.Execution.Coordination.FeatureCoordinator.Dispose()
   at LightBDD.XUnit2.LightBddScopeAttribute.TearDown()
   at LightBDD.XUnit2.Implementation.Customization.TestFrameworkExecutor.RunTestCases(IEnumerable`1 testCases, IMessageSink executionMessageSink, ITestFrameworkExecutionOptions executionOptions)
   at Xunit.Sdk.TestFrameworkExecutor`1.RunTests(IEnumerable`1 testCases, IMessageSink executionMessageSink, ITestFrameworkExecutionOptions executionOptions) in /_/src/xunit.execution/Sdk/Frameworks/TestFrameworkExecutor.cs:line 100
   at Xunit.Xunit2.RunTests(IEnumerable`1 testCases, IMessageSink messageSink, ITestFrameworkExecutionOptions executionOptions) in /_/src/xunit.runner.utility/Frameworks/v2/Xunit2.cs:line 110
   at Xunit.XunitFrontController.RunTests(IEnumerable`1 testMethods, IMessageSink messageSink, ITestFrameworkExecutionOptions executionOptions) in /_/src/xunit.runner.utility/Frameworks/XunitFrontController.cs:line 185
   at TestFrameworkExtensions.RunTests(ITestFrameworkExecutor executor, IEnumerable`1 testCases, IMessageSinkWithTypes executionMessageSink, ITestFrameworkExecutionOptions executionOptions) in /_/src/xunit.runner.utility/Extensions/TestFrameworkExtensions.cs:line 69
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in /_/src/xunit.runner.visualstudio/VsTestRunner.cs:line 555
```

I have a custom `IReportWriter` implementation that relies on an `IFeatureConfiguration` exposing a service which resolve an output directory at runtime. This unfortunately fails runtime since the `FeatureCoordinator` uninstalls itself before disposing the feature aggregator. 

This can easily be fixed by swapping the following two consecutive lines in `FeatureCoordinator`:

https://github.com/LightBDD/LightBDD/blob/c07341ea8dc90d5c2dae74650d9bdad848978100/src/LightBDD.Core/Execution/Coordination/FeatureCoordinator.cs#L120-L121

#### Progress

- [ ] Feature is implemented,
- [ ] Ensured backward-compatibility,
- [ ] Ensured good debugging experience

**Comment by Suremaker** [comment]
Included in LighBDD 3.8.0. Thanks @goldsam for your contribution!
