### ISSUE TITLE
Simplify exception stack trace by removing LightBDD internal calls and filter test framework specific calls

### ISSUE THREAD

**Issue by Suremaker** [LightBDD/LightBDD#69]
#### Description
Currently when exception is thrown, a long call stack if being captured for LightBDD internal calls.
Consider:
* wrap scenario/step exceptions in transport exception that will hide LightBDD internal stack frames,
* add configuration allowing to exclude frames representing underlying test framework assertion code (like Assert.That() etc)

#### Progress

- [x] Implement transport exception,
- [x] Update basic syntax to wrap exceptions as soon as possible,
- [x] Update extended syntax to wrap exceptions as soon as possible,
- [x] Update decorators to wrap exceptions as soon as possible,
- [x] Update synchronous runners to unwrap exceptions as late as possible,
- [x] Update asynchronous runners to unwrap exceptions as late as possible,
- [x] Implement frame filtering for underlying test framework assertion code,
- [x] Ensured backward-compatibility,
- [x] Ensured good debugging experience
- [x] Post implementation refactoring

**Comment by Suremaker** [comment]
Sample scenario:
```c#
[Label("SCENARIO-1")]
[Scenario]
public void Template_extended_scenario()
{
	Runner.RunScenario(
		_ => Given_method(),
		_ => When_method(),
		_ => Then_method());
}
private void Given_method()
{
}

private void When_method()
{
}

private void Then_method()
{
	Assert.Fail("Not implemented yet");
}
```

Before changes (R# output window):
```
Not implemented yet
at ClassLibrary1.My_feature1.Then_method() in c:\tmp\LightBDD-Compat\ClassLibrary1\My_feature1.Steps.cs:line 18
at lambda_method(Closure , NoContext , Object[] )
at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.InvocationResultTransformer.<InvokeAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepMethodAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepMethodAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightBDD.Core.Execution.Implementation.RunnableStep.<InvokeStepAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightBDD.Framework.Commenting.Implementation.StepCommentingDecorator.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightBDD.Core.Execution.Implementation.RunnableStep.<TimeMeasuredInvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightBDD.Core.Execution.Implementation.RunnableStep.<RunAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at LightBDD.Core.Execution.Implementation.RunnableScenario.<RunAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.RunSynchronously()
at ClassLibrary1.My_feature1.Template_extended_scenario() in c:\tmp\LightBDD-Compat\ClassLibrary1\My_feature1.cs:line 30


SCENARIO: [SCENARIO-1] Template extended scenario
  STEP 1/3: GIVEN method...
  STEP 1/3: GIVEN method (Passed after 12ms)
  STEP 2/3: WHEN method...
  STEP 2/3: WHEN method (Passed after <1ms)
  STEP 3/3: THEN method...
  STEP 3/3: THEN method (Failed after 3ms)
  SCENARIO RESULT: Failed after 137ms
    Step 3: NUnit.Framework.AssertionException : Not implemented yet
    	at NUnit.Framework.Assert.ReportFailure(String message)
    	at ClassLibrary1.My_feature1.Then_method() in c:\tmp\LightBDD-Compat\ClassLibrary1\My_feature1.Steps.cs:line 18
    	at lambda_method(Closure , NoContext , Object[] )
    	at LightBDD.Core.Extensibility.Implementation.ScenarioRunner.InvocationResultTransformer.<InvokeAsync>d__5.MoveNext()
```

After changes:
```
Not implemented yet
at ClassLibrary1.My_feature1.Then_method() in c:\tmp\LightBDD-Compat\ClassLibrary1\My_feature1.Steps.cs:line 18
at lambda_method(Closure , NoContext , Object[] )
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at LightBDD.Framework.Scenarios.Extended.ExtendedScenarioExtensions.RunScenario[TContext](IBddRunner`1 runner, Expression`1[] steps)
at ClassLibrary1.My_feature1.Template_extended_scenario() in c:\tmp\LightBDD-Compat\ClassLibrary1\My_feature1.cs:line 30


SCENARIO: [SCENARIO-1] Template extended scenario
  STEP 1/3: GIVEN method...
  STEP 1/3: GIVEN method (Passed after <1ms)
  STEP 2/3: WHEN method...
  STEP 2/3: WHEN method (Passed after <1ms)
  STEP 3/3: THEN method...
  STEP 3/3: THEN method (Failed after 1ms)
  SCENARIO RESULT: Failed after 6ms
    Step 3: NUnit.Framework.AssertionException : Not implemented yet
    	at ClassLibrary1.My_feature1.Then_method() in c:\tmp\LightBDD-Compat\ClassLibrary1\My_feature1.Steps.cs:line 18
    	at lambda_method(Closure , NoContext , Object[] )
```
